["Library/PreferencePanes/Cursorcerer.prefPane"]
    type = "archive"
    url = "https://www.doomlaser.com/downloads/Cursorcerer.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "720h"

[".local\\share\\fonts\\MesloLGS NF Regular.ttf"]
    type = "file"
    url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
    refreshPeriod = "720h"

[".local\\share\\fonts\\MesloLGS NF Bold.ttf"]
    type = "file"
    url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
    refreshPeriod = "720h"

[".local\\share\\fonts\\MesloLGS NF Italic.ttf"]
    type = "file"
    url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
    refreshPeriod = "720h"

[".local\\share\\fonts\\MesloLGS NF Bold Italic.ttf"]
    type = "file"
    url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
    refreshPeriod = "720h"
